language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

os:
  - linux

env:
  - COMPOSER_FLAGS="--prefer-lowest"
  - COMPOSER_FLAGS=""

matrix:
  include:
    - php: 5.4
      env: BUILD_PHAR=true
    - php: 7.1
      env: COVERAGE=yes
    - php: 7.1
      env: EXECUTE_CS_CHECK=yes
  allow_failures:
    - php: nightly

before_install:
  - source .travis/travis.sh
  - if [[ $TRAVIS_PHP_VERSION != hhvm && $TRAVIS_PHP_VERSION != nightly && $COVERAGE != yes ]]; then phpenv config-rm xdebug.ini; fi
  - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - travis_retry composer self-update

install:
  - travis_retry composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction $COMPOSER_FLAGS

before_script:
  - git config --global user.email "travis-ci@codeclimate.com"
  - git config --global user.name "Travis CI"
  - mkdir -p "$HOME/.php-cs-fixer"

script:
  - composer validate
  - if [[ $COVERAGE == yes ]]; then vendor/bin/phpunit --coverage-clover=build/logs/clover.xml; else vendor/bin/phpunit --no-coverage; fi
  - if [[ $EXECUTE_CS_CHECK == yes ]]; then php -n -d memory_limit=768M vendor/bin/php-cs-fixer fix --config=.php_cs --verbose --diff --dry-run; fi

after_success:
  - if [[ $COVERAGE == yes ]]; then php composer/bin/test-reporter; fi

deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file: build/codeclimate-test-reporter.phar
  skip_cleanup: true
  on:
    tags: true
    php: 5.4
    condition: "$BUILD_PHAR == true"
